#include "../inc/minishell.h"

// TODO
// - leaks are generated by not handling quote errors correctly
// example:	char	*input_str = "< infile ls -l | wc -l > outfile'";

char	**split_line(char *input_str)
{
	int		i;
	int		start;
	int		no_word;
	int		total_words;
	char	**words;

	i = 0;
	start = 0;
	no_word = 0;
	total_words = count_words(input_str);
	words = malloc(sizeof(char *) * (total_words + 1));
	if (!words)
		return (NULL);

	// switches
	int expand = 1;
	int single_quote = 0;
	int double_quote = 0;

	while (input_str[i] != '\0')
	{
		// start copying char by char

		// if " found, switch off >expand<
		// if ' found, switch on >expand<
		// if white=space found, reallocate,

	}
	i = 0;
	words[total_words] = NULL;
	return (words);
}