/* ************************************************************************** */
/*																			*/
/*														:::	  ::::::::   */
/*   get_cmd_path.c									 :+:	  :+:	:+:   */
/*													+:+ +:+		 +:+	 */
/*   By: mheinze <mheinze@student.42.fr>			+#+  +:+	   +#+		*/
/*												+#+#+#+#+#+   +#+		   */
/*   Created: 2022/10/04 21:08:49 by mheinze		   #+#	#+#			 */
/*   Updated: 2022/11/22 16:15:23 by mheinze		  ###   ########.fr	   */
/*																			*/
/* ************************************************************************** */

#include "../inc/minishell.h"

// TODO
// - leaks are generated by not handling quote errors correctly
// example:	char	*input_str = "< infile ls -l | wc -l > outfile'";

char	**split_line(char *input_str)
{
	int		i;
	int		start;
	int		no_word;
	int		total_words;
	char	**words;
	char	*tmp;

	i = 0;
	start = 0;
	no_word = 0;
	input_str = ft_strtrim(input_str, " 	");
	tmp = ft_strtrim(input_str, " 	");
	free(input_str);
	input_str = tmp;
	total_words = count_words(input_str);
	words = malloc(sizeof(char *) * (total_words + 1)); // leak gets fixed by freeing return value in main loop
	if (!words)
		return (NULL);
	while (input_str[i] != '\0')
	{
		start = i;
		while (!ft_strchr("\'\" 	", input_str[i]) && input_str[i] != '\0')
			i++;
		if (i > start)
		{
			if (ft_strchr(" 	", input_str[i]))
				i++;
			words[no_word++] = ft_substr(input_str, start, i - start);
			continue;
		}
		if (input_str[i] == '\'' || input_str[i] == '\"')
		{
			if (input_str[i + quote_length(input_str[i], input_str, i) + 2] == ' ')
			{
				i = i + quote_length(input_str[i], input_str, i) + 2;
				words[no_word++] = ft_substr(input_str, start, i - start + 1);
			}
			else
			{
				i = i + quote_length(input_str[i], input_str, i) + 1;
				words[no_word++] = ft_substr(input_str, start, i - start + 1);
			}
		}
		i++;
	}
	free(input_str);
	words[total_words] = NULL;
	return (words);
}